resources:
  repositories:
  - repository: hive-net  
    endpoint: ive-net-gitlab
    type: git
    name: hive-net  
    ref: master
 
trigger:
- none
 
pool:
  vmImage: 'windows-latest'
 
steps:
- checkout: self
- checkout:  hive-net 