trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
    - checkout: self
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-o $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'nuget'
        publishLocation: 'pipeline'
    - task: NuGetCommand@2
      displayName: 'Push to nuget.org'
      inputs:
        command: 'push'
        packagesToPush: './artifacts/*.nupkg;!./artifacts/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'SplinterbotsNugetOrg'
        allowPackageConflicts: true