resources:
  repositories:
  - repository: hive-net  
    endpoint: Repos - MSFTPlayground
    type: git
    name: msft-ccoe/msft-ccoe
    ref: master
  - repository: hive-net 
    name: Azure DevOps Discovery/Governance
    type: git
    ref: master
 
trigger:
- none
 
pool:
  vmImage: 'windows-latest'
 
steps:
- checkout: self
- checkout: DifferentOrganization
- checkout: SameOrganization
- script: dir $(Build.SourcesDirectory)